[package]
name = "kodbot"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
toml_edit = "0.20"
twilight-http = "0.15"
twilight-model = "0.15"
tokio = { version = "1", features = ["full"] }
