[package]
name = "kodbot"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "model", "rustls_backend"] }
tokio = { version = "1", features = ["full"] }
