guild = "407149490307334144"

[welcome]
channel = "557097166573666304"
file = "welcome.msg"

[ebas]
url = "https://ebas.ungvetenskapssport.se/apis"

[member]
role = "944005544560185385"

[member.permission]
# Only let @Styrelsen purge membership status
purge = [{ role = "407150862046199808" }]