**Välkommen till Kodsports Discord-server!** <:kodsport:730139604296138886>

Vi är en ideell förening som driver tävlingar, läger, träffar och annat inom programmering och datasäkerhet. För att få ta del av vår verksamhet kan du [bli medlem i föreningen](<https://ebas.ungvetenskapssport.se/blimedlem/kodsport>). Du kan sedan verifiera ditt medlemskap i Discord med kommandot `/member verify <email>`.

För att det ska vara trevligt på servern så har vi följande regler man ska förhålla sig till:

<:ac:519296526644936705> Ställ gärna frågor kring de tävlingar, läger, träffar och andra saker vi anordnar!

<:ac:519296526644936705> Diskutera problemlösning, programmering och datorsäkerhet, här finns det kunniga människor som kan det mesta!

<:ac:519296526644936705> Var välkomnande och inkluderande. Kom ihåg att alla inte har samma erfarenhet och kunskaper och vi är här för att lära varandra!

<:ac:519296526644936705> Spoiler-markera gärna lösningar `||såhär||`.

<:ac:519296526644936705> Håll er till ämnet i de olika kanaler som finns.

<:ac:519296526644936705> Följ [Discords riktlinjer](<https://discord.com/guidelines>).

<:wa:519296548069441556> Publicera inte uppgifter från pågående tävlingar eller som generellt ska hållas hemliga.

<:wa:519296548069441556> Fråga inte om hjälp med uppgifter som ni ska lösa själva i skolan eller under en tävling. Publicera inte heller lösningar på sådana problem.

<:wa:519296548069441556> Spammeddelanden är förbjudet.

<:wa:519296548069441556> Skicka inte NSFW-bilder/videor/texter eller diskriminerande meddelanden.

Bryter du mot ovanstående regler kan du bli banlyst.

Om det dyker upp någon fråga eller fundering så kan du kontakta <@&407150862046199808>.